[project]
name = "genaigrader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.1",
    "ollama>=0.4.8",
    "openai>=1.78.1",
    "packaging>=25.0",
    "requests>=2.32.3",
    "whitenoise>=6.9.0",
]
