# Generated by Django 5.1.4 on 2025-03-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_course_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='username',
            new_name='user',
        ),
    ]
