# Generated by Django 5.1.4 on 2025-05-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genaigrader', '0005_model_api_key_model_api_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='creator_username',
            new_name='user',
        ),
    ]
